# Generated by Django 6.0.3 on 2026-03-31 23:24

import django.core.validators
import django.db.models.deletion
import necroporra.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('wikidata_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{5}$', 'Slug must be exactly 5 alphanumeric characters')])),
                ('timeframe_choice', models.CharField(choices=[('end_of_year', 'End of current year'), ('end_of_next_year', 'End of next year'), ('1_month', '1 month from now'), ('3_months', '3 months from now'), ('6_months', '6 months from now'), ('1_year', '1 year from now')], default=necroporra.models.get_default_timeframe, help_text='When the pool will end', max_length=20)),
                ('limit_date', models.DateTimeField(blank=True, help_text='The date when the pool becomes inactive', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Public pools can be discovered by slug code; private pools require a valid invitation link')),
                ('allow_member_invite_links', models.BooleanField(default=True, help_text='For private pools, allow non-admin members to copy invitation links')),
                ('max_predictions_per_user', models.IntegerField(default=10, help_text='Maximum number of predictions each user can make', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_locked', models.BooleanField(default=False, help_text='Whether this pool is closed (picks are visible and predictions are frozen)')),
                ('lock_after_days', models.IntegerField(blank=True, help_text='Days after pool creation when the pool closes (1-7)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('lock_date', models.DateTimeField(blank=True, help_text='The date when the pool will close', null=True)),
                ('scoring_mode', models.CharField(choices=[('simple', 'Simple - 1 point per correct prediction'), ('distributed', 'Distributed - Allocate 10 points across predictions')], default='simple', help_text='How points are calculated for correct predictions', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(help_text='The current admin of the pool. Deleting this user deletes the pool.', on_delete=django.db.models.deletion.CASCADE, related_name='pools_administered', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, help_text='The user who originally created the pool.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoolCelebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_death_recorded', models.BooleanField(default=False, help_text="Has this celebrity's death been recorded?")),
                ('manual_death_date', models.DateField(blank=True, help_text='Death date manually set by the pool admin. Ignored once Celebrity.death_date is set by Wikidata.', null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_lists', to='necroporra.celebrity')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrities', to='necroporra.pool')),
            ],
            options={
                'unique_together': {('pool', 'celebrity')},
            },
        ),
        migrations.CreateModel(
            name='PoolInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_invitations_created', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='necroporra.pool')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('pool',), name='unique_active_invitation_per_pool')],
            },
        ),
        migrations.CreateModel(
            name='PoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('wins', models.IntegerField(default=0, help_text='Number of correct predictions (for simple mode)')),
                ('total_points', models.IntegerField(default=0, help_text='Total points earned (for distributed mode)')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='necroporra.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points', '-wins'],
                'unique_together': {('pool', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(help_text='None=undecided, True=correct, False=wrong', null=True)),
                ('weight', models.IntegerField(default=1, help_text='Weight assigned to this prediction (for distributed scoring)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('points_earned', models.IntegerField(blank=True, help_text='Points earned from this prediction after scoring', null=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='necroporra.celebrity')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='necroporra.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'pool', 'celebrity')},
            },
        ),
    ]
