# Generated by Django 6.0.2 on 2026-02-18 20:32

from django.db import migrations
from dateutil.relativedelta import relativedelta


def populate_limit_dates(apps, schema_editor):
    """Populate limit_date and timeframe_choice from legacy timeframe_years."""
    Pool = apps.get_model('necroporra', 'Pool')
    
    for pool in Pool.objects.all():
        if pool.timeframe_years:
            # Calculate limit_date from created_at + timeframe_years
            pool.limit_date = pool.created_at + relativedelta(years=pool.timeframe_years)
            
            # Set timeframe_choice based on years
            if pool.timeframe_years == 1:
                pool.timeframe_choice = '1_year'
            elif pool.timeframe_years == 2:
                pool.timeframe_choice = '1_year'  # No exact match, use 1_year
            elif pool.timeframe_years == 3:
                pool.timeframe_choice = '1_year'  # No exact match, use 1_year
            elif pool.timeframe_years == 5:
                pool.timeframe_choice = '1_year'  # No exact match, use 1_year
            else:
                pool.timeframe_choice = '1_year'  # Default
            
            pool.save()


def reverse_populate_limit_dates(apps, schema_editor):
    """Reverse migration - nothing to do since we're keeping timeframe_years."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('necroporra', '0002_alter_poolmembership_options_remove_pool_is_active_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_limit_dates, reverse_populate_limit_dates),
    ]
