# Generated by Django 6.0.2 on 2026-02-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necroporra', '0006_pool_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolcelebrity',
            name='manual_death_date',
            field=models.DateField(blank=True, help_text='Death date manually set by the pool admin. Ignored once Celebrity.death_date is set by Wikidata.', null=True),
        ),
    ]
