# Generated by Django 6.0.2 on 2026-03-04 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_null_admins(apps, schema_editor):
    """
    Ensure no Pool has admin=NULL before the column becomes non-nullable.
    Sets admin to creator for any pool missing an admin.
    Deletes pools that have neither admin nor creator (orphaned).
    """
    Pool = apps.get_model('necroporra', 'Pool')
    null_admin_pools = Pool.objects.filter(admin__isnull=True)
    for pool in null_admin_pools:
        if pool.creator:
            pool.admin = pool.creator
            pool.save(update_fields=['admin'])
        else:
            # No admin and no creator — orphaned pool, remove it
            pool.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('necroporra', '0007_add_manual_death_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First backfill NULL admins so the non-nullable constraint can be applied
        migrations.RunPython(backfill_null_admins, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pool',
            name='admin',
            field=models.ForeignKey(help_text='The current admin of the pool. Deleting this user deletes the pool.', on_delete=django.db.models.deletion.CASCADE, related_name='pools_administered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pool',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user who originally created the pool.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
