# Generated by Django 6.0.2 on 2026-03-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necroporra', '0012_seed_pool_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='allow_member_invite_links',
            field=models.BooleanField(default=True, help_text='For private pools, allow non-admin members to copy invitation links'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public pools can be discovered by slug code; private pools require a valid invitation link'),
        ),
    ]
