# Generated by Django 6.0.2 on 2026-03-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('necroporra', '0013_pool_allow_member_invite_links_alter_pool_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='description',
        ),
    ]
