# Generated by Django 6.0.2 on 2026-02-18 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necroporra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poolmembership',
            options={'ordering': ['-total_points', '-wins']},
        ),
        migrations.RemoveField(
            model_name='pool',
            name='is_active',
        ),
        migrations.AddField(
            model_name='pool',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public pools can be discovered; private pools require the slug code'),
        ),
        migrations.AddField(
            model_name='pool',
            name='limit_date',
            field=models.DateTimeField(blank=True, help_text='The date when the pool becomes inactive', null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='max_predictions_per_user',
            field=models.IntegerField(default=10, help_text='Maximum number of predictions each user can make', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='pool',
            name='picks_visibility_date',
            field=models.DateTimeField(blank=True, help_text='The date when picks will become visible', null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='picks_visible',
            field=models.BooleanField(default=False, help_text="Whether users can see each other's predictions"),
        ),
        migrations.AddField(
            model_name='pool',
            name='picks_visible_after_days',
            field=models.IntegerField(blank=True, help_text='Days after pool creation when picks become visible (0-7, null if visible from start)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='pool',
            name='scoring_mode',
            field=models.CharField(choices=[('simple', 'Simple - 1 point per correct prediction'), ('dynamic', 'Dynamic - Points based on difficulty (TBD)'), ('distributed', 'Distributed - Allocate 10 points across predictions')], default='simple', help_text='How points are calculated for correct predictions', max_length=20),
        ),
        migrations.AddField(
            model_name='pool',
            name='timeframe_choice',
            field=models.CharField(choices=[('1_month', '1 month from now'), ('3_months', '3 months from now'), ('6_months', '6 months from now'), ('1_year', '1 year from now'), ('end_of_year', 'End of current year'), ('end_of_next_year', 'End of next year')], default='1_year', help_text='When the pool will end', max_length=20),
        ),
        migrations.AddField(
            model_name='poolmembership',
            name='total_points',
            field=models.IntegerField(default=0, help_text='Total points earned (for dynamic/distributed modes)'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='points_earned',
            field=models.IntegerField(blank=True, help_text='Points earned from this prediction after scoring', null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='weight',
            field=models.IntegerField(default=1, help_text='Weight assigned to this prediction (for distributed scoring)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='pool',
            name='timeframe_years',
            field=models.IntegerField(blank=True, default=1, help_text='DEPRECATED: Use timeframe_choice and limit_date instead', null=True),
        ),
        migrations.AlterField(
            model_name='poolmembership',
            name='wins',
            field=models.IntegerField(default=0, help_text='Number of correct predictions (for simple mode)'),
        ),
    ]
