# Generated by Django 6.0.2 on 2026-02-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('necroporra', '0003_populate_limit_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='timeframe_years',
        ),
    ]
