# Generated by Django 6.0.2 on 2026-02-25 21:04

import django.db.models.deletion
import necroporra.models
from django.conf import settings
from django.db import migrations, models


def set_admin_to_creator(apps, schema_editor):
    """Populate Pool.admin with the pool's creator for existing rows."""
    Pool = apps.get_model('necroporra', 'Pool')
    Pool.objects.filter(admin__isnull=True).update(admin=models.F('creator'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('necroporra', '0005_remove_dynamic_scoring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='The current admin of the pool. Defaults to the creator.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools_administered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_admin_to_creator, reverse_code=noop),
        migrations.AlterField(
            model_name='pool',
            name='timeframe_choice',
            field=models.CharField(choices=[('end_of_year', 'End of current year'), ('end_of_next_year', 'End of next year'), ('1_month', '1 month from now'), ('3_months', '3 months from now'), ('6_months', '6 months from now'), ('1_year', '1 year from now')], default=necroporra.models.get_default_timeframe, help_text='When the pool will end', max_length=20),
        ),
        migrations.AlterField(
            model_name='poolmembership',
            name='total_points',
            field=models.IntegerField(default=0, help_text='Total points earned (for distributed mode)'),
        ),
    ]
