# Generated by Django 6.0.2 on 2026-03-17 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necroporra', '0008_cascade_admin_set_null_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='picks_visibility_date',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='picks_visible',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='picks_visible_after_days',
        ),
        migrations.AddField(
            model_name='pool',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Whether this pool is locked (picks are visible and predictions are frozen)'),
        ),
        migrations.AddField(
            model_name='pool',
            name='lock_after_days',
            field=models.IntegerField(blank=True, help_text='Days after pool creation when the pool locks (1-7)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='pool',
            name='lock_date',
            field=models.DateTimeField(blank=True, help_text='The date when the pool will lock', null=True),
        ),
    ]
